language: android

jdk:
  - oraclejdk8

install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; then curl https://dl.google.com/android/repository/tools_r25.2.5-linux.zip > $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; fi
  - unzip -n $HOME/android-sdk-dl/tools_r25.2.5-linux.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager --licenses
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;25.0.3'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-25'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-19'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'emulator'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'system-images;android-19;default;armeabi-v7a'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;google_play_services'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository'

before_script:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

  - export ANDROID_SDK_ROOT=$HOME/android-sdk/

  # Create and start an emulator for instrumentation tests.
  - echo no | $HOME/android-sdk/tools/bin/avdmanager create avd -f -n test -k "system-images;android-19;default;armeabi-v7a"
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - "./gradlew build cAT jacocoTestReport"

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache
